version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    restart: on-failure:10
    ports:
      - "80:80"
    volumes:
      - ./app.db:/app/bin/app.db
      - ./app.db-shm:/app/bin/app.db-shm
      - ./app.db-wal:/app/bin/app.db-wal
